# Generated by Django 3.2.12 on 2022-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220206_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('usage', models.TextField()),
                ('example', models.TextField()),
                ('dop', models.TextField(blank=True)),
                ('category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.URLField(max_length=300),
        ),
    ]
