# Generated by Django 3.2.12 on 2022-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220209_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
